applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'persona_app'

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path('listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
        ),
    path(
        'listar-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path(
        'lista-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('buscar-empleado/',
        views.ListEmpleadosByKword.as_view(),
        name='buscar_empleado'
        ),
    path(
        'listar-habilidades-empleado/<id>/',
        views.ListHabilidadesEmpleado.as_view(),
        name='habilidades_empleados'
    ),
    path('ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
        ),
    path('add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
        ),
    path(
        'success/',
        views.SucessView.as_view(),
        name='correcto'
    ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluir urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    # Incluir urls de la app persona
    re_path('', include('applications.persona.urls')),
    # Incluir urls de la app home
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.

class Habilidades(models.Model):
    """Model definition for Habilidades."""

    # TODO: Define fields here
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        """Meta definition for Habilidades."""

        verbose_name = 'Habilidade'
        verbose_name_plural = 'Habilidades Empleados'

    def __str__(self):
        """Unicode representation of Habilidades."""
        return str(self.id) + '-' + self.habilidad

class Empleado(models.Model):
    """ Modelo para tabla empleado  """

    # TODO: Define fields here
    JOB_CHOICES = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Facturacón'),
        ('4', 'Recaudación'),
        ('5', 'Sistemas'),
        ('6', 'Mantenimiento'),
        ('7', 'Otro'),
    )

    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField(
        'Nombres Completos',
        max_length=120,
        blank=True
    )
    job = models.CharField('Trabajo', max_length=50, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    class Meta:
        """Meta definition for Empleado"""

        verbose_name = 'Mi Empledado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['first_name', 'last_name']
        unique_together = ('first_name', 'departamento')


    def __str__(self):
        return self.first_name + '-' + self.last_name

applications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'first_name' : forms.TextInput(attrs={'placeholder': 'Nombre'}),
            'last_name' : forms.TextInput(attrs={'placeholder': 'Apellidos'}),
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

#import en una linea
#from django.views.generic import ListView, DetailView, CreateView

#import en mas de una linea
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)


# Models
from .models import Empleado
# forms
from .forms import EmpleadoForm


class InicioView(TemplateView):
    """ Vista que carga la pagina de Inicio(home)"""
    template_name = "inicio.html"


# Create your views here.
class ListAllEmpleados(ListView):
    template_name = "persona/list_all.html"
    paginate_by = 5
    ordering = 'first_name'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword','')
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
            )
        return lista


class ListaEmpleadosAdmin(ListView):
    template_name = "persona/lista_empleados.html"
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado


class ListByAreaEmpleado(ListView):
    """ Lista empleados de una area    """
    template_name = "persona/list_by_area.html"
    context_object_name = 'empleados'

    def get_queryset(self):
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__shor_name = area
        )
        return lista


class ListEmpleadosByKword(ListView):
    """ Lista empleado por clave"""
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleado'

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword','')
        lista = Empleado.objects.filter(first_name = palabra_clave)
        return lista


class ListHabilidadesEmpleado(ListView):
    """ Lista habilidades de un empleado """
    template_name = 'persona/habilidades.html'
    tmp_var='Hola Vista'
    context_object_name = 'habilidades'

    def get_queryset(self):
        id = self.kwargs['id']
        empleado = Empleado.objects.get(id=id)
        return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empelado del Mes'
        return context


class SucessView(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"
    form_class = EmpleadoForm


    #fields = ('__all__') # Para agregar todos los campos del Modelo
    # fields = [
    #     'first_name',
    #     'last_name',
    #     'job',
    #     'departamento',
    #     'habilidades',
    #     'avatar',
    # ]

    #success_url = '.' # Para que se recargue en la misma pagina
    success_url = reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        # Logica del proceso
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
    ]

    success_url = reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('**************METODO POST******************')
        print('=========================')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        # Logica del proceso
        print('**************METODO FORM VALID******************')
        print('=========================')
        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy('persona_app:empleados_admin')

templates/persona/add.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Registrar Empleado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Registrar Empleado</h1>
                <form class="grid-x grid-margin-x" method="post" enctype="multipart/form-data"> {% csrf_token %}
                    <div class="medium-6 cell">
                        <label>Nombres:
                            {{form.first_name}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Apellidos:
                            {{form.last_name}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Trabajo:
                            {{form.job}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Area:
                            {{form.departamento}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Habilidades extra:
                            {{form.habilidades}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Foto:
                            {{form.avatar}}
                        </label>
                    </div>
                    <div class="cell">
                        <button type="submit" class="success button">Guardar</button>
                    </div>
                </form>
        </div>
    </div>
{% endblock content %}

templates/persona/by_kword.html
<h1>Buscar empelado por palabra clave</h1>
<form  method="GET">{% csrf_token %}
    <input type="text" name="kword" id="kword" placeholder="Ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

{% if empleado %}
    <h3>Lista resultados</h3>
    <lu>
        {% for e in  empleado %}
            <li>
                {{e}}
            </li>
        {% endfor %}
    </lu>
{% endif %}

templates/persona/delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Eliminar Empleado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Eliminar Empleado: {{ object.full_name}}</h1>
                <form class="cell" method="post"> {% csrf_token %}
                    <div class="callout secondary">
                        <h5>¿desea eliminar este empleado?</h5>
                        <button type="submit" class="alert button">Confirmar</button>
                    </div>
                </form>
        </div>
    </div>
{% endblock content %}


<h1>Eliminar Empleado</h1>

<form method="post"> {% csrf_token %}
    <p>Confirne que desea eliminar</p>
    <button type="submit">Confirmar</button>
</form>

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
{{object.full_name}}
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
                <div class="card-divider">
                    {{ empleado.get_job_display }}
                </div>
                {% if empleado.avatar %}
                    <img src="{{ empleado.avatar.url }}">
                {% else %}
                    <img src="{% static 'img/default-avatar.jpg' %}">
                {% endif %}
                <div class="card-section">
                    <h4>{{ empleado.full_name }}</h4>
                    <p>{{ empleado.first_name }}</p>
                    <p>{{ empleado.departamento.shor_name }}</p>
                    <p><span class="label">Habilidades</span></p>
                        <ul>
                            {% for h in empleado.habilidades.all %}
                                <li>{{ h.habilidad }}</li>
                            {% endfor %}
                        </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/persona/habilidades.html
<h1>habilidades de empleado</h1>
{{ empleado }}

<ul>
    
    {% for h in habilidades %}
        <li>
            {{ h }}
        </li>
    {% endfor %}
        
</ul>

templates/persona/list_all.html
{% extends 'base.html' %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar Empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="150">ID</th>
                    <th width="150">NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150" style="text-align: center">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                    <!--  for empleado in object_list
                        Para cuando no se declare el context_object_name
                        en la vista.
                    -->
                    {% for empleado in empleados %}
                        <tr>
                            <td>{{empleado.id}}</td>
                            <td>{{empleado.first_name}}</td>
                            <td>{{empleado.last_name}}</td>
                            <td>{{empleado.departamento}}</td>
                            <td style="text-align: center;"><a class="button warning" href=" {% url 'persona_app:empleado_detail' empleado.id %}">Ver</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination text-center">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                        </li>
                        {% endif %}

                        {% for pagina in paginator.page_range %}

                        {% ifequal pagina page_obj.number  %}
                        <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                        {% else %}
                        <li><a href="?page={{pagina}}">{{ pagina }}</a></li>
                        {% endifequal %}

                        {% endfor %}

                        {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Lista de empleados por Área
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Empleados por Área:</h1>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="150">ID</th>
                            <th width="150">NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARTAMENTO</th>
                            <th width="150" style="text-align: center;">ACCION</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for empleado in empleados  %}
                        <tr>
                            <td>{{empleado.id}}</td>
                            <td>{{empleado.first_name}}</td>
                            <td>{{empleado.last_name}}</td>
                            <td>{{empleado.departamento}}</td>
                            <td style="text-align: center;"><a class="button warning" href=" {% url 'persona_app:empleado_detail' empleado.id %}">Ver</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="150">ID</th>
                    <th width="150">NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150" colspan="2" style="text-align: center;">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                    <!--  for empleado in object_list
                        Para cuando no se declare el context_object_name
                        en la vista.
                    -->
                    {% for empleado in empleados %}
                        <tr>
                            <td>{{empleado.id}}</td>
                            <td>{{empleado.first_name}}</td>
                            <td>{{empleado.last_name}}</td>
                            <td>{{empleado.departamento}}</td>
                            <td>
                                <a class="button success" href="{% url 'persona_app:modificar_empleado' empleado.id %}">Editar</a>
                            </td>
                            <td>
                                <a class="button alert" href="{% url 'persona_app:eliminar_empleado' empleado.id %}">Eliminar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination text-center">
                        {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                        </li>
                        {% endif %}

                        {% for pagina in paginator.page_range %}

                        {% ifequal pagina page_obj.number  %}
                        <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                        {% else %}
                        <li><a href="?page={{pagina}}">{{ pagina }}</a></li>
                        {% endifequal %}

                        {% endfor %}

                        {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/success.html
<h1>Felicidades se guardo correctamente el empleado</h1>

templates/persona/update.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Modificar Datos del Empleado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Modificar Datos del Empleado</h1>
            <div class="cell">
                <form class="grid-x grid-margin-x" method="post"> {% csrf_token %}
                    <div class="cell large-6">
                        <label>Nombres:
                            {{form.first_name}}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>Apellidos:
                            {{form.last_name}}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>Trabajo:
                            {{form.job}}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>Area:
                            {{form.departamento}}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>Habilidades extra:
                            {{form.habilidades}}
                        </label>
                    </div>
                    <div class="cell">
                        <button type="submit" class="success button">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}