applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'departamento_app'

urlpatterns = [
    path(
      'departamento-lista/',
      views.DepartamentoListView.as_view(),
      name='departamento_list'
    ),
    path(
      'new-departamento/',
      views.NewDepartamentoView.as_view(),
      name='nuevo_departamento'
    ),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'persona_app'

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path('listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
        ),
    path(
        'listar-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path(
        'lista-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path('buscar-empleado/',
        views.ListEmpleadosByKword.as_view(),
        name='buscar_empleado'
        ),
    path(
        'listar-habilidades-empleado/<id>/',
        views.ListHabilidadesEmpleado.as_view(),
        name='habilidades_empleados'
    ),
    path('ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
        ),
    path('add-empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
        ),
    path(
        'success/',
        views.SucessView.as_view(),
        name='correcto'
    ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
    ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluir urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    # Incluir urls de la app persona
    re_path('', include('applications.persona.urls')),
    # Incluir urls de la app home
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField('Nombre Corto', max_length=20)
    anulate = models.BooleanField('Anulado', default=False)

    def __str__(self):
        return self.name + '-' + self.shor_name

applications/departamento/forms.py
from django import forms

class NewDepartamentoForms(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView

from applications.persona.models import Empleado
from .models import Departamento

from .forms import NewDepartamentoForms


# Create your views here.

class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = 'departamentos'


class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForms
    success_url = '/'

    def form_valid(self, form):
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            shor_name = form.cleaned_data['shorname']
        )
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']

        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '1',
            departamento = depa
        )

        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Lista Departamentos
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{ departamento.name }}</td>
                            <td>{{ departamento.shor_name }}</td>
                            <td style="text-align: center;"><a class="button warning " href="{% url 'persona_app:empleados_area' departamento.shor_name %}">Ver Empleados</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Registrar Departamento
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Registrar Departamento</h1>
                <form class="cell callout grid-x grid-margin-x" method="post" enctype="multipart/form-data"> {% csrf_token %}
                    <div class="medium-6 cell">
                        <label>Nombres:
                            {{form.nombre}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Apellidos:
                            {{form.apellidos}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Departamento:
                            {{form.departamento}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Nombre Corto Departamento:
                            {{form.shorname}}
                        </label>
                    </div>
                    <div class="cell">
                        <button type="submit" class="success button">Guardar</button>
                    </div>
                </form>
        </div>
    </div>

{% endblock content %}

<h1>Registrar nuevo departamento</h1>

<form method="post"> {% csrf_token %}
    <h3>Datos Empleado</h3>
    <p>
        Nombre: {{form.nombre}}
    </p>
    <p>
        Apellidos: {{form.apellidos}}
    </p>
    <h3>Datos del Departamento</h3>
    <p>
        Nombre del Departamento: {{form.departamento}}
    </p>
    <p>
        Nombre corto departamento: {{form.shorname}}
    </p>
    <button type="submit">Guardar</button>
</form>